# Generated by Django 6.0.2 on 2026-02-26 14:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0002_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='coefficient',
        ),
        migrations.RemoveField(
            model_name='note',
            name='valeur',
        ),
        migrations.AddField(
            model_name='note',
            name='note_examen',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Examen /8'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_rattrapage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Rattrapage /20'),
        ),
        migrations.AddField(
            model_name='note',
            name='note_test',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Test /12'),
        ),
        migrations.AlterField(
            model_name='note',
            name='professeur',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gestion.professeur'),
            preserve_default=False,
        ),
    ]
