# Generated by Django 6.0.2 on 2026-03-02 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0004_alter_note_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='coursemploidutemps',
            name='date_modification',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
